# Generated by Django 4.1.3 on 2022-12-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='номер аккаунта')),
                ('account_type', models.IntegerField(default=1, verbose_name='тип аккаунта')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('citizenship', models.CharField(default='Кыргызстан', max_length=20, verbose_name='гражданство')),
                ('birth_year', models.DateField(verbose_name='год рождения')),
                ('work_place', models.CharField(blank=True, max_length=30, null=True, verbose_name='место работы')),
                ('update_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='сумма кредита')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата получения кредита')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.account', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'db_table': 'loans',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='credit.client'),
        ),
    ]
